### ISSUE TITLE
Feature request: Implementation for Unicode CLDR standard rule for transiliteration

### ISSUE THREAD

**Issue by miurahr** [miurahr/unihandecode#17]
ICU support every languages in the world except CJKV Kanji/Hanji.

http://userguide.icu-project.org/transforms/general

ICU follows http://www.eki.ee/wgrs/ 

We should make compatibility with ICU conversion or link with ICU.

**Comment by besfahbod** [comment]
Fwiw, we use unihandecode alongside ICU in our Natural Text Processing library, to enable romanization across all scripts. Making this library open source is in the plans, but haven't materialized yet. I'd be happy to chat offline if you like to know more details. :)

**Comment by miurahr** [comment]
Current implementation uses preliminary data from unidecode project.
It is better to make a database from Unicode standard CLDR specification.
 
http://cldr.unicode.org/index/cldr-spec/transliteration-guidelines

 Chinese, Korean pronunciation data is produced from Unihan database from Unicode standard in unihandecode.

To make compatibility with ICU means mostly standard conformance with Unicode standard.

A purpose of the issue is not 'use unihandecode alongside ICU', but implement database and logic which is compatible with ICU.
